---
 
 - hosts: all
   become: true
   pre_tasks:
 
   - name: update repository index
     yum:
       name: '*'
       state: latest
     when: ansible_distribution == "Amazon"
 
   - name: install updates (Ubuntu)
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"
 
 
 - hosts: web_servers
   become: true
   tasks:
 
   - name: install package
     tags: amazon nginx, amazon php
     yum:
       name:
         - nginx
         - php
       state: latest
     when: ansible_distribution == "Amazon"

 
   - name: install package (Ubuntu)
     tags: ubuntu apache2, ubuntu php
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: copy default html file to apache default
     tags: ubuntu_file
     copy:
       src: default.html
       dest: /var/www/html/index.html
       owner: ubuntu
       group: ubuntu
       mode: 0644
     when: ansible_distribution == "Ubuntu"

   - name: copy default html file to nginx default
     tags: amazon_file
     copy:
       src: default.html
       dest: /usr/share/nginx/html/index.html
       owner: ec2-user
       group: ec2-user
       mode: 0644
     when: ansible_distribution == "Amazon"

   - name: Copy default html file to nginx default
     tags: amazon_file
     copy:
       src: nginx.conf
       dest: /etc/nginx/nginx.conf
       owner: ec2-user
       group: ec2-user
       mode: 0644
     when: ansible_distribution == "Amazon"
     register: nginx_conf

   - name: Restart nginx
     tags: amazon_nginx_restart
     service:
       name: nginx
       state: restarted
     when: nginx_conf.changed
 
 - hosts: db_servers
   become: true
   tasks:
 
   - name: Install MariaDB server
     yum:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Amazon"
 
   - name: install mariadb server
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"
 
